- software/control/_def.py
- software/main_hcs.py
- software/octopi/logging.py
- software/squid/logging.py
- software/tests/squid/test_logging.py
This adds logging tools in the squid.logging module (along with the squid package), and two helpers there for getting loggers and setting the squid logger logging level. This allows us to have a dedicated hierarchy of loggers that we can configure while leaving all the loggers setup by other libraries alone.
It also adds an example usage in the control._def.py module. We can start converting individual files after this.
It also lays the groundwork for better crash reports by allowing us to hook up handlers for uncaught exceptions. By default these just print to console, but we want to be able to hook up a FileHandler to our logger and have the uncaught exceptions go there as well. Actually creating the FileHandler and attaching it to the root squid logger is to come.
NOTE: This was …
> logging: add logging mechanism, hooks to log uncaught crashes, and an example use of the logging tools

- software/control/gui.py
- software/control/gui_hcs.py
- software/control/gui_malaria.py
- software/main.py
- software/main_hcs.py
- software/main_malaria.py
- software/squid/logging.py
See title.  This is just straight conversion of prints to `Logger`, and other small tweaks along the way.
> software/main_*: Delete unused imports, convert the main and gui* to use loggers.

- software/main_hcs.py
- software/main_malaria.py
- software/squid/logging.py
- software/tests/squid/test_logging.py
This makes it so we can start logging to a file, and have users send the file upon crashing.  It's setup such that, regardless of `set_stdout_log_level`, all logs down to `DEBUG` go to the file.
Tested by: Unit tests, and running `main_hcs.py` with and without `--verbose` and making sure that log output appears in stdout and the log file as expected.
> logging: add a helper for registering a rotating file log that captures all output regardless of stdout log level

- software/control/camera_TIS.py
- software/control/camera_ids.py
- software/control/camera_toupcam.py
- software/control/camera_tucsen.py
This starts converting all the camera implementations to using loggers, and marks a lot of `TODO` where we need to come back and do error handling.
> control/camera_toupcam: use loggers

- software/squid/logging.py
See title.  This is a debug message formatting-only change.
Tested by: Running `python main_hcs.py --simulation`
> logging: add missing close quote in logging message

- .gitignore
See title.  This just adds to the .gitignore.
Tested by: `git status` no longer shows `.idea` directories.
> gitignore: add .idea/ directories.

- software/control/gui.py
- software/control/gui_hcs.py
- software/control/gui_malaria.py
- software/control/microcontroller.py
Before, the `Microcontroller_Simulation` implementation was a bunch of copy/pasted code from the `Microcontroller` simulation.  This wasn't ideal because we needed to keep them in sync for simulation to reflect reality, and since we needed to have some small differences (eg: no reader thread) we weren't testing the actual `Microcontroller` code paths in simulation mode.
this moves the simulation stub down one level to `Serial`, and sets it up so we can have custom simulated serial implementations in the future that, for instance, can keep track of positions and act more like the real firmware.
> microcontroller: for simulation, use a stub serial device instead of copy/pasted implementation

- software/control/microcontroller.py
This changes the command logic so that there's the notion of aborted commands.  These are relevant in 2 cases:
1. Internal to the `Microcontroller` implementation, if the reader thread doesn't get a command ack in time or the microcontroller responds with too many checksum errors, a command is aborted.
2. a user of `Microcontroller` can call `abort_current_command` to force the current command to abort.  This is useful if the wait function throws a `TimeoutError` - the caller can abort the command and move on.
IMPORTANT NOTE: right now, aborting a command does not tell the microcontroller to do anything.  AKA if a motion is in progress, it'll continue.  We could change this behavior but I'm not sure what the correct behavior is.
> microcontroller: add the notion of aborted commands, and throw TimeoutError on failed waits

- firmware/octopi_firmware_v2/main_controller_teensy41/main_controller_teensy41.ino
Tested By: Running a handful of captures with 405nm excitation on a fluorescing slide.  Before this fix, we'd get a few black frames every time.  After this fix, we were unable to reproduce the black frames.
> firmware: fix bug where hardware trigger interrupt was able to access partially written data

- software/control/core.py
- software/control/gui_hcs.py
- software/control/widgets.py
fix incomplete conversion from 0 -> "glass slide" for representing slide format
> sample format bug fix (glass slide)

- software/control/core.py
- software/control/gui_hcs.py
- software/control/widgets.py
- removed from NavigationViewer
- update_slide() 
- signal_update_well_coordinates = Signal(bool)
- same as clear slide, since scan grid overlay is now separate image item
- removed update slide from HighContentScreeningGui
- removed from NavigationViewer
- draw_scan_grid() 
- signal_update_live_scan_grid = Signal(float, float)
- self.acquisition_started
- instead directly connect navigationController to wellplateMultipointWidget to draw to NavigationViewer instead of going from navigationController through NavigationViewer to signal wellplateMultipointWidget to draw to NavigationViewer
- self.navigationController.scanGridPos.connect(self.wellplateMultiPointWidget.set_live_scan_coordinates)  
- added self.is_live_scan_grid_on in HighContentScreeningGui
- can disconnect if not 'glass …
> signal cleanup: remove redundant signals, streamline acquisition signal and slot logic

- software/control/widgets.py
- the flexible scan regions are still shown instead of the manual region, even if it is edited/altered and triggers a signal
- manual ROI is only available from wellplateMultiPointWidget and not flexibleMultiPointWidget
- toggle manual/draw mode on 
- switch to select vertex mode if a shape already exists
- switch to add polygon mode if no shapes
- toggle manual/draw mode off
- switch to pan/zoom and leave shapes layer if toggled off
> bug fix: edits to manual region shape should not update scan coordinates while on flexible widget

- software/squid/abc.py
- software/squid/config.py
- software/squid/exceptions.py
- software/squid/stage/cephla.py
- software/squid/stage/prior.py
- software/squid/stage/utils.py
- software/tests/squid/test_config.py
- software/tests/squid/test_stage.py
This is starting work on the "X, Y, Z Motion stage" task in https://www.notion.so/cephla/Headless-Mode-and-Scripting-Design-1452dfbf6ae480c3b444ee0847f532a5 .
It's gonna be a tricky one - we have stage-like code in a lot of places.  But the net result is that we will end up deleting a ton of tricky code (eg: all the unit conversion stuff) from a bunch of places, and instead have it all focused in one location.
The hard part isn't the stage implementation, it's finding all the places we do stage-like stuff, fixing them, and making sure nothing is broken in the process.
> interface: start pulling out the stage concept

- software/control/core/core.py
- software/control/gui_hcs.py
- software/control/widgets.py
Workflow
- click checkbox - "Focus Map" in in wellplate/flexibleMultiPointWidget
- creates grid of focus points that we can navigate to and set the Z level
- fits 3d surface from the focus points when we start acquisition
- interpolates and updates z level for each fov of each region
FocusMapWidget:
- in cameraTabWidget (can be moved to recordTabWidget)
- add, remove, next, edit buttons
- set grid size with spinbox for rows x cols
- until sufficient # points set
- select a focus point in dropdown menu to navigate to it
- update z level of the current focus point
FocusMap:
- handles the math for fitting 3d surface from a set of x,y,z points
- need at least 4 points to fit surface 
- 'spline' or 'rbf' surface fitting methods
- smoothing factor for surface fitting 
NavigationViewer:
- green …
>  focus-map: (manual focus point grid) - specify z level at points, fit to 3d surface, interpolate for acquisition scan fovs

- software/control/gui_hcs.py
This is a simplified #51 that keeps full position updates for anyone that wants to listen.
Tested by: Running both a simulated and real system, and making sure the red current fov box renders on the plate as expected.
> fix: send pos from movement updater, and start movement updater

- software/control/widgets.py
before this (1) set_live_scan_coordinates will be called even if the stage is not moving (2) set_live_scan_coordinates can happen too frequently - problematic for big scan area coverage
> prevent constant update of scan coordinate preview

- software/tests/control/test_microcontroller.py
@veerwang fixed the relative move `Microcontroller` bug in #66 , so we no longer need to special case the test for relative moves.  The behavior is correct now.
Tested By: Unit tests pass!
> fix(microcontroller): microcontroller test rel moves are correct now

- .github/workflows/black.yml
We weren't using `--check` before, so this adds it.  This will make the linting actions fail if the changes aren't properly formatted.
Tested by: This should fail the linting action!  If it does because of required formatting, then this is good to go.
> fix(lint action): Fail linting action if formatting would have happened

- software/control/core/core.py
This just adds in more debugging for the case when auto focus fails, and gives an explicit printout in our acquisition loop if autofocus fails (and makes it clear that we just continue anyway!).
This just adds debugging, and shouldn't affect actual behavior.
Also a few logic cleanups to quiet the ide linter.
Tested by:  I ran this on a system with autofocus.  To get autofocus to fail, I had it scan onto a plate edge where it wouldn't find the 2 laser autofocus dots and made sure that the scan continued (but that we got printouts).
> debug(laser af): only catch Exception, print exec_info, indicate failure for caller in autofocus method

- software/control/core/core.py
- software/control/gui_hcs.py
- software/control/widgets.py
`34713ec14805b441a1cee7dbeb2c13c337035d31` added the `self.is_current_acquisition_widget` concept on our acquisition widgets.  This was set to `= False` in two places for each - one in the `toggle_acquisition` and another in `acquisition_finished`.  The `toggle_acquisition` always ran first (it sent the signal that eventually resulted in `acquisition_finished` getting called), which means that the code in `acquisition_finished` was always skipped via the `if` guard checking for `is_current_acquisition_widget`.
It's not clear if we need `is_current_acquisition_widget` since it's new-ish, but for now leave it and just make it so `acquisition_finished` is the only `= False` setter of that flag.
Tested by: running local acquisitions.  Before this, the stage control + acquisition widgets would …
> fix(acquisition abort): Aborting acquisitions midway left the ui in an invalid state

- software/control/core/core.py
Reported by @Alpaca233 .
This is not the long term solution - we should be able to handle single timeouts (when a retry succeeds).  But we do need some top level mechanism to make sure the gui doesn't wedge in a useless state.
Tested by: Tests pass, and a local sim with a `raise TimeoutError()` in `def run` behaves as expected.
> acquisitions: catch TimeoutErrors in acquisitions, and abort acquisition cleanly

- software/control/core/core.py
- software/control/core_PDAF.py
- software/control/core_platereader.py
- software/control/core_usbspectrometer.py
- software/control/utils.py
- software/control/widgets.py
- software/tools/script_create_zarr_from_acquisition.py
This fixes the case of selecting a save path that does not exist.  As long as you have permissions to create all the directories leading to your chosen path, they will be created for you.
Tested by: Setting my save path to `/home/ian/does/not/exist/Downloads` and making sure acquisitions succeed and put the results there.  Before this change, acquisition failed with that save path (which does not exist).  Unit tests also still pass.
> utils: add a directory creation helper, and use it instad of os.mkdirs

- software/control/gui_hcs.py
- software/squid/stage/prior.py
Stages need a config.  We should make the `PriorStage` config non-optional, but for now just make sure to pass it in.
> fix(stage): pass in PriorStage config when using Prior

- software/squid/stage/prior.py
Add a background polling timer so we know the `PriorStage` position is never more than 0.25 sec out of date.
> stage: prior: add a position polling timer

- software/control/core/core.py
We were only checking fov centers before.  This now also checks corners.  It isn't perfect - if you have a sharp point, it won't be included unless you get lucky and the bounding box grid has corners in it.
Tested by: On system testing
> manual regions: add corner check for inclusion criteria

- software/control/gui_hcs.py
- software/control/microcontroller.py
- software/control/microscope.py
- software/tests/control/test_microcontroller.py
- software/tests/control/test_microscope.py
- software/tests/squid/test_stage.py
We know our long running acquisitions can sometimes hang.  We think this is, at least sometimes, due to serial hiccups.  This adds a mechanism for automatic reconnect of our `Microcontroller` serial device.  For now, it does not add this same functionality to all our `serial_peripheral` devices, but doing so should be easy.
This does not handle the cases of a caller specifying a timeout, and the timeout elapsing.  In those cases, the caller is responsible for catching the `TimeoutError` and doing something about it.
Tested by: Running a local sim, and running acquisitions on a real system.  When running on the real system, I unplugged and plugged the microcontroller USB a bunch during acquisitions.  The only time I got it to not resume was when I got an "mcu operation timed out" …
> feat(microcontroller): Add a mechanism for automatic serial reconnect, and use it

- software/control/core/core.py
- software/control/widgets.py
This was a bug whereby if you aborted, and then spammed the start button, you could cause the ui to crash.
This stops this from happening by checking to see if the worker thread is still running.  If it is, we don't allow another to start.
Tested by: running on the Prior system.
> acquistions: when we abort, do not let another start until previous is finished

- software/control/core/core.py
- software/setup_22.04.sh
- software/tests/control/gui_test_stubs.py
- software/tests/control/test_MultiPointWorker.py
This makes sure the attribute is always set regardless of the config.  It also adds a basic unit test mechanism for the gui / business logic code that we can start using to test all this stuff.
Tested by: Unit tests
> fix: napari init attrib bug, and add unit tests

- software/control/utils.py
- software/main_hcs.py
- software/tests/control/test_utils.py
This is important for us to be able to track down user submitted bugs.  Right now, it's impossible to know what code they're running if they send the sha1 with their report.
Tested by: Unit test, and making sure that running main_hcs results in the correct printed sha1 locally.
> logging&utils: add helper for getting squid repo state, log state on startup

- software/configurations/configuration_HCS_v2.ini
- software/configurations/configuration_Squid+.ini
- software/configurations/configuration_Squid+_H117_ORCA.ini
- software/control/_def.py
- software/control/core/core.py
- software/control/gui_hcs.py
- software/control/piezo.py
- software/control/widgets.py
Major changes:
- Add dedicated PiezoStage class to encapsulate piezo functionality
- Add Z stage configuration system with three modes (stepper_only, piezo_only, stepper_and_piezo)
- Use piezo for laser autofocus when available (closed-loop control)
- Rename ENABLE_OBJECTIVE_PIEZO to HAS_OBJECTIVE_PIEZO for clarity
Technical improvements:
- Add type hints and docstrings to piezo-related code
- Add range validation for piezo movements
- Add configuration options for piezo parameters
- Centralize piezo control logic in one class
Configuration changes:
- Add Z_STAGE_CONFIG section to .ini files
- Add z_stage_mode option with three modes
- Maintain backward compatibility with Z_MOTOR_CONFIG
> feat: improve piezo stage control

- software/control/core/core.py
- software/control/widgets.py
- software/tests/control/gui_test_stubs.py
- software/tests/control/test_gui_config_editors.py
This fixes a user reported bug whereby config saves with invalid (or impermissible) file paths would fail silently.
Tested by: Both unit tests, and a local sim test to make sure the error dialog pops up.
> fix: for both config editors, catch and alert on file permission errors

- software/control/core/core.py
fix distance moved for calibration factor calculation
> laser af init bug fix

- software/control/gui_hcs.py
- software/tests/control/test_HighContentScreeningGui.py
We weren't handling the `False` case for piezo presence.  This fixes that, and adds a basic test to make sure we can instantiate the high content screening gui with or without the piezo.
Tested by: Added a unit test to make sure we can at least create the gui with or without a piezo.
> fix: handle piezo presence/absence

- software/control/core/core.py
Tested by: Unit tests now close up cleanly.
> fix: daemonize process queue threads so we get clean close even if signals are missed.

- software/control/core/core.py
- software/control/utils_config.py
- software/control/widgets.py
1. Add reference state tracking:
- Add has_reference flag to LaserAutofocusController
- Add has_reference to LaserAFConfig for persistence
- [to add] reference_crop storage for cross-correlation checks
2. Update LaserAutofocusControlWidget UI:
- Disable measure/move buttons until reference is set
- Enable buttons only after successful reference set
- Update button states based on controller's has_reference state
3. Add validation for multipoint acquisition:
- Check for reference before allowing laser AF acquisition
- Show warning dialog if acquisition attempted without reference
- Re-enable UI if validation fails
This ensures proper laser autofocus usage by:
- Preventing measure/move operations without reference
- Maintaining reference state across sessions
- Providing clear user feedback …
> feat: enforce laser autofocus reference requirement

- software/control/_def.py
- software/control/core/core.py
- software/control/gui_hcs.py
- software/control/utils.py
- software/control/widgets.py
- software/main_hcs.py
- Fixed passing params for spot detection. Previously it's using default params
- Show crosshair on spot centroid location
- Display cross-correlation result
- Checkbox for turning on / off laser af characterization mode
> Improve Laser-Based Focus display to show results of running laser autofocus 

- software/squid/logging.py
This is a reported bug from a windows user.  The logging system was tripped up by the lower case mu character.
I don't have a system that can replicate the issue, but this seems likely since there are some documented cases of windows defaulting to ascii.
Tested By: I cannot test this locally.  There used to be a `sys.setdefaultencoding` hack, but it sounds like the default encoding is hard coded past python 3.8 (see [here](https://stackoverflow.com/questions/2276200/changing-default-encoding-of-python).  I could force FileHandler to use ascii, but that doesn't really seem like an actual test...
> fix(logging): Make sure our file handler uses unicode and continues through errors

- software/control/core/core.py
- software/control/gui_hcs.py
- software/control/widgets.py
- Automatically turn off focus camera live on switching tab
- Hide well selector on focus camera live tab
- Show calibration value when loaded from cache
- Fix laser af characterization mode
- Ensure update on loading new profiles
> laser autofocus UX improvement

- software/control/microscope.py
- software/tests/control/gui_test_stubs.py
- software/tests/control/test_MultiPointWorker.py
- software/tests/tools.py
Most of the fixes here are just changed object structures, not actual bugs.  But the `microscope.py` initialization issues are real and would prevent `microscope.py` from working as expected.
Tested by: More unit tests pass now.  There's still 1 test that segfaults on a `QApplication.processEvents()` call, but not because of changes here.
> fix(tests): microscope init test fix, other argument change fixes

- .github/workflows/main.yml
- software/control/core/core.py
The `processEvents` call is at the end of a callback method, so it really doesn't do anything (we immediately give control back to Qt after).  But it was causing segfaults in the abort acquisition test (which might be another problem?).
Also we were getting aborted test runs on our workflows.  I think it's because we don't have a proper x environemnt.  xvfb gives us that.
Tested by: Unit tests
> testing: add xvfb-run so we have a proper x environment, and remove a trailing processEvents call

- software/control/gui_hcs.py
- software/control/microcontroller.py
- software/squid/stage/cephla.py
- software/tests/control/test_MultiPointWorker.py
- software/tests/control/test_microcontroller.py
We weren't setting limits on boot.  Adding in the limits exposes an issue whereby the microcontroller allows a pos limit < neg limit.  In this case, the microcontroller hangs / refuses / ignores all subsequent moves to that axis and demonstrates bizarre behavior.
This fixes that by making sure to swap the pos and neg limits if the axis direction is flipped.
To pretect against other future issues, this also plumbs the homing direction down through `CephlaStage` since switching these could have caused problems.
Tested by:  Booting the GUI now results in a proper working z axis, and the z axis stays at the minimum limit after homing (instead of driving to the max position!).  Also, I added a unit test for homing direction testing.
> stage + gui: set limits, and fix limit direction bug

- software/control/camera_toupcam.py
- software/control/core/core.py
- software/control/utils.py
- software/control/utils_acquisition.py
- software/control/widgets.py
- software/tests/control/test_MultiPointController.py
- software/tests/control/test_utils.py
This adds in tools for:
1. Checking how many images an acquisition will use
2. Checking how much disk space an acquisition will use
3. For both flexible and well multi point acquisition widgets, using those tools to prevent acquisitions from starting if there isn't enough memory.
Separately, we want to add the disk usage info to the ui after an acquisition starts.  That will be done in a follow up PR.
Tested By: Unit tests for the helpers, and testing different acquisition to make sure small ones succeed and large ones do not start.
> gui: acquisitions: prevent acquisitions from starting if there is not enough disk space

- software/control/utils.py
- software/squid/abc.py
- software/squid/camera/utils.py
- software/squid/config.py
- software/tests/squid/test_camera.py
This adds the AbstractCamera and simulated camera, but without touching existing machinery.  A follow up PR will integrate this into the system.
Tested by: unit test on simulated camera creation and basic functionality.
> squid: abc: Add the AbstractCamera interface, and a simulated camera implementation

- software/control/core/core.py
- software/control/gui_hcs.py
- software/control/microscope.py
- software/squid/abc.py
The live controller was receiving half-illuminated frames after stopping live mode.  This gives us a mechanism for telling the StreamHandler to ignore frames if a boolean function does not return true, and then we use it everywhere.
Tested by: On system testing.
> StreamHandler: allow providing an accept fn, and use it for the live controller

- software/control/widgets.py
- software/squid/config.py
This fixes a bug in the handling of camera pixel format setting in our camera widget.
Tested by: On system testing.
> widgets: camera control: fix pixel format

- software/control/camera.py
- software/control/camera_hamamatsu.py
- software/squid/abc.py
- software/squid/camera/utils.py
- software/squid/config.py
- software/tests/squid/test_camera.py
- software/tools/camera_stress_test.py
We inconsistently raised `CameraError` or returned `None` in `read_camera_frame` before.  Now we always return `None` if a read fails, and we handle this case in the `read_frame` historical method.
This is via a bug reported where laser autofocus spot detect would fail on the `self.read_camera_frame().frame` in the `read_frame` implementation.  
Tested By: Unit test, and a script modified to stress test all cameras (not just the hamamatsu).  Also local sim still works.
> cameras: None frame error universal, add test and test script

- software/squid/camera/utils.py
- software/tests/squid/test_camera.py
- software/tools/camera_stress_test.py
This fixes the simulated camera such that it replicates the behavior of the other cameras: you need to send a trigger to get frames, unless in continuous streaming mode.
It also fixes the continuous streaming mode for the sim cam which was broken before, and caused printouts even when not in continuous streaming mode.
NOTE: There's still an issue whereby we do not turn off streaming after acquisitions, or properly turn off streaming after live mode.  So sometimes if you're in continuous mode, you'll see that frames are still streamed (because we don't turn off streaming).  This is a separate issue that we need to fix.
Tested By: Unit tests pass, also when in simulated gui mode no printouts from the streaming thread occur unless in continuous triggering mode.
> camera: simulated: fix continuous streaming mode, exposure, other

- software/control/core/core.py
- software/control/widgets.py
- software/tools/microcontroller_stress_test.py
We have one user that runs long acquisitions, and occasionally gets `TimeoutError` on `wait_till_operation_complete`.  There is likely a deeper issue going on since this really should never happen in their use case (the send_trigger and microcontroller laser on/off operations should happen quickly, so timing out after 3 or 5 seconds indicates some larger serial/microcontroller issue).
This also introduces a script to try to test the microcontroller.  Example usage:
```
python tools/microcontroller_stress_test.py --laser_af --runtime 600 --stage --on_thread --no_loop_sleep
```
I haven't successfully replicated this failure yet, though.
Tested By: This is not tested yet!  I need access to a system that has laser AF.
> laser af microcontroller use: attempt to handle occasional timeouts

- software/control/microscope.py
This fixes microscope.py's camera creation.
Tested by: Hongquan tested this on hw.
> microscope: fix CameraPixelFormat args

- software/squid/camera/utils.py
- software/tests/control/test_utils.py
We get errors when running this as a github action because qt is pre-loaded, and it conflicts with tk.  It isn't critical, so to get the tests running skip it for now.
Also, now that tests are running it revealed the width,height swap in the simulated camera `_next_frame`.  This also fixes that.
Tested By: Workflow must pass!
> tests: skip debug plot test because backend

- software/control/microscope.py
If users did not have laser AF turned on, and don't have the gxipy laser af camera plugged in, they couldn't init a Microscope before this.  Now they can.
Tested by: Running a script that initializes a microscope on hardware without a laser af camera.
> microscope: fix focus camera init to only be with focus cam

- software/tools/stage_timing.py
This is a script for testing Microscope z axis timings.  For now it is really simple, but we can expand on it as we do more and more stage / microscope performance testing.
Tested by: Use on a CephlaStage.
> tools: add stage timing test script

- firmware/octopi_firmware_v2/main_controller_teensy41/main_controller_teensy41.ino
We were not packing the return message checksum before, so the client code couldn't check for corrupted (or offset) messages.  This adds it.
Tested by: Flashing a system and running `tools/microcontroller_stress_test.py` for a while.
> firmware: calculate and put checksum in return packets

- software/control/microcontroller.py
- software/tools/microcontroller_stress_test.py
This makes sure the incoming crc are correct, and if not scans along the read buffer trying to find a valid message border.  It also changes our logic to get rid of the exact packet length match in favor of just requiring enough bytes for a valid packet.
Tested By: Running `tools/microcontroller_stress_test.py` for a while with #195 on the firmware side.  I also tested without #195 on the firmware side to make sure that case still works.
> microcontroller: ignored packets with bad checksums, scan input buffer

- software/control/microcontroller.py
This will tell us if new data is still coming in from the microcontroller.  If we don't see printouts, valid packets are coming in.
Tested by: I set the stale timeout to <10ms to make sure this prints out.  Also, I ran the stress test with `--no_wait` which locks up responses on the microcontroller.  Both of these made prints occur.
> Microcontroller: Add a read-staleness watchdog (sortof) so we can see if new data is coming in

- software/tools/stage_timing.py
This is just a modification to our stage testing script so we get nicer results, and can test in a bunch of different scenarios.
Example usage:
```
$ python tools/stage_timing.py --start 1.000 --step 0.001 --axis=z --count 100
$ python tools/stage_timing.py --start 1.100 --step -0.001 --axis=z --count 100
```
Tested by: Tested on CephlaStage a bunch.
> tools: stage timing: allow any axis, start and step, no home

- software/control/core/core.py
- software/control/microscope.py
- software/squid/stage/cephla.py
- software/tools/stage_timing.py
Before, we'd do z backlash compensation in one-off and sortof inconsistent ways.  Also, the `PriorStage` has its own internal backlash compensation, so in that case we'd be doubling up on backlash compensation.
This changes our convention to always do backlash compensation in the stage implementation, so users do not need to care (and always get backlash compensation if doing blocking calls).
The next step is to move backlash compensation down to the embedded level, but I looked into doing that today and it was not straightforward.
Tested by:
1. Running a small acquisition
2. Run the stage timing script a bunch for z axis moves.
> z movement: move backlash compensation into CephlaStage so it is universal

- software/squid/stage/cephla.py
Our default was to use ~30um backlash compensation.  This means that for a 1um move in the -z direction, we actually do a -31um move, then a 30um move.  A 30um move takes about 100 ms on the CephlaStage, which means that 1 um move with backlash compensation took about 200ms!
For reference, a 1um move without backlash compensation takes about 40 ms.
Changing our backlash compensation to 5um gets a 1um move with backlash compensation down to about 125 ms.
Tested by:  Running the `tools/stage_timing.py` script before and after both with and without `--relative`.
> stage: cephla: change backlash comp from 30um to 5um for speed

- software/control/widgets.py
This pull request modifies the `save_coordinates` method in `software/control/widgets.py` to enhance functionality for saving scan coordinates for multiple objectives. The changes include restructuring the file naming logic and adding the ability to save coordinates for all objectives in the `objectiveStore`.
* **Saving coordinates for multiple objectives**: Added functionality to iterate through all objectives in `objectiveStore`, save their respective scan coordinates to separate files, and then restore the current objective after saving. ([software/control/widgets.pyR4514-R4528](diffhunk://#diff-26413fa85447f35aa4077535ae2d5f6f1905d5de96d6b303d426f9d039ddde2bR4514-R4528))
> save coordinates for all objectives

- software/control/utils_config.py
Revert changing the data type of `x_offset` and `y_offset` from `float` to `int` because this may break user laser AF profile.
> revert the change in LaserAFConfig base model

- software/control/widgets.py
This pull request modifies the `clearAllLayers` method in `software/control/widgets.py` to preserve the "Manual ROI" layer while clearing the contents of all other layers. It also ensures that the viewer layers are refreshed after clearing. 
Key changes in `clearAllLayers`:
* The method now skips the "Manual ROI" layer when clearing layers, ensuring its content remains intact.
* For other layers, it creates an empty array matching the layer's dimensions and data type (supports both RGB and Grayscale formats) and assigns it to `layer.data`.
* After clearing, the method refreshes each layer to reflect the changes.
Tested in simulation mode
> keep manual ROI after clearing mosaic view

- software/control/fluidics.py
This pull request introduces a new emergency stop mechanism to the `fluidics.py` module, ensuring safe handling of operations when an emergency stop is triggered. The changes add a flag to track the emergency stop state and modify key methods to respect this state.
* **Added `emergency_stop_called` flag**: Introduced a new instance variable, `self.emergency_stop_called`, to track whether an emergency stop has been activated. This flag is initialized to `False` in the constructor (`__init__`).
* **Updated `emergency_stop` method**: Modified the `emergency_stop` method to set the `emergency_stop_called` flag to `True` when an emergency stop is triggered.
* **Reset emergency stop state**: Added logic to reset the `emergency_stop_called` flag to `False` in the `set_rounds` method, ensuring …
> fix emergency stop for fluidics widget

- software/control/core/core.py
This just removes a few unused pieces in MultiPointController.  They are "known unused" via `ag` their name on the whole repo.
Tested by: running some acqusitions, aborts, etc.  Also unit tests pass.
> MultiPointController: remove a few risk free unused bits

- software/control/lighting.py
We will need to call microcontroller.set_illumination() whether there's an intensity update or not, otherwise we cannot set the current channel.
> illumination control bug fix: setting current channel

- software/control/core/core.py
This pull request introduces a new status bar and related functionality to enhance user interaction in the `software/control/core/core.py` file. The changes include adding a status bar to display cursor position, pixel value, stage position, and piezo position, implementing real-time updates for stage and piezo positions, and improving cursor tracking within the image view.
* Added a status bar with labels for cursor position, pixel value, stage position, and piezo position, initialized with default values. These labels are displayed at the bottom of the main layout. ([1](diffhunk://#diff-2fc90167f3cd3e8a6b36bdd78086c6ae5811054d9f87239fa2fe2b3a8858d691R2981-R3025), [2](diffhunk://#diff-2fc90167f3cd3e8a6b36bdd78086c6ae5811054d9f87239fa2fe2b3a8858d691L3027-R3079))
* Introduced a `QTimer` to …
> add status bar to live display to show cursor pixel value and stage position

- software/control/core/core.py
- software/control/widgets.py
This pull request introduces a new feature to enable image acquisition for the current field of view (FOV) and adds a "Snap Images" button to the user interface. The changes include updates to the acquisition logic, user interface components, and the integration of the new button functionality. Below are the most important changes grouped by theme:
* Modified the `run_acquisition` method in `software/control/core/core.py` to accept a new parameter, `acquire_current_fov`. This enables acquisition for the current FOV by setting appropriate scan region coordinates and flags.
* Updated the `_on_acquisition_completed` method to reset the `run_acquisition_current_fov` flag after the acquisition process is completed.
* Added a "Snap Images" button in `software/control/widgets.py` and integrated …
> add the ability to snap multi channel images of the current FOV

- software/control/core/core.py
This pull request simplifies the handling of pixel value display and error cases in the `core.py` file by removing unnecessary checks and formatting changes. The key changes focus on improving code readability and consistency.
* Removed the `hasattr` check for the `image` attribute in `handle_mouse_move` and directly accessed the `image` property, assuming its presence.
* Simplified the pixel value display by removing the `.2f` formatting for floating-point values in both `handle_mouse_move` and `display_image`. This ensures consistent display without unnecessary precision. [[1]](diffhunk://#diff-2fc90167f3cd3e8a6b36bdd78086c6ae5811054d9f87239fa2fe2b3a8858d691L3322-R3334) [[2]](diffhunk://#diff-2fc90167f3cd3e8a6b36bdd78086c6ae5811054d9f87239fa2fe2b3a8858d691L3497-R3493)
* Replaced complex …
> pixel value display int instead of float, no display when cursor off image

- software/control/core/multi_point_worker.py
These were missed in the rebase required for #217 
Tested by: Running a small acquisition in simulation mode.  It'd fail before this.
> bug: fix crop_width and crop_height usage (they no longer exist)

- software/squid/logging.py
This is helpful for debugging since we have multiple threads in play in multiple areas.
Tested by: The logging unit tests still pass.
> logging: add thread id to our log lines

- software/configurations/configuration_HCS_v2.ini
- software/control/camera.py
- software/control/camera_toupcam.py
- software/control/widgets.py
- software/squid/abc.py
- software/squid/camera/utils.py
- software/squid/config.py
This pull request introduces several updates to enhance camera configuration, add support for new camera models, and implement temperature reading callbacks. The most significant changes include enabling temperature reading callbacks across camera modules, adding support for the Hamamatsu camera model, and updating camera configuration options.
* Added a new abstract method `set_temperature_reading_callback` to the base camera interface (`software/squid/abc.py`) to support temperature reading callbacks.
* Implemented the `set_temperature_reading_callback` method in `camera_toupcam.py`, replacing the previously private `_set_temperature_reading_callback` method.
* Restored the temperature reading callback functionality in the widget interface by connecting the callback to …
> camera bug fix: temperature reading; Hamamatsu model config; Squid configuration file 

- software/control/camera_hamamatsu.py
- software/control/camera_photometrics.py
This pull request includes updates to the camera control software to improve exposure time handling and optimize performance. The changes focus on ensuring consistent exposure time units across different camera models and avoiding unnecessary operations to enhance efficiency.
* [`software/control/camera_hamamatsu.py`](diffhunk://#diff-d6cb813e4a91ece8b40a46cc9255b3fbd30991a7a4a3e3eca8c796ff14416775L201-R201): Adjusted the `get_exposure_limits` method to convert exposure time limits from seconds to milliseconds for consistency with other methods.
* [`software/control/camera_photometrics.py`](diffhunk://#diff-23a4bc5c57c95dc0d00bcabf405aded068e842d342e105b4206a18781ddd6b90R252-R255): Updated the `set_exposure_time` method to check if the new exposure time matches the current value, avoiding …
> camera fix: Kinetix camera set exposure time and Hamamatsu camera get exposure time range

- software/control/core/core.py
- software/control/core/multi_point_worker.py
- software/control/gui_hcs.py
- software/control/widgets.py
This is not a totally complete "decouple the ui" PR, but is a stepping stone to get there.  Before, we used `MultiPointWorker.signal_current_configuration -> MultiPointController.signal_current_configuration -> LiveControlWidget.set_microscope_mode -> dropdown text change signal -> update mode from name -> LiveController.set_microscope_mode` to update the hardware settings for each acquisition frame.  This was a lot of qt machinery to work through!
Instead, this directly calls `LiveController.set_microscope_mode` and separately signals updating the ui.  And the `LiveControlWidget` is changed so that it calls `LiveController.set_microscope_mode` only when a new user selected value is triggered (and otherwise, only updates the ui).
This would be better without the …
> microscope mode selection: do it directly, and only use signals for ui updates

- software/control/core/core.py
- software/control/core/multi_point_worker.py
This is step 1 of 2 to get to full overlapped triggering acquisitions.  This adds in the callback mechanism in `MultiPointWorker` for handling frames asynchronously, but only triggers one frame at a time (and uses the `threading.Event()` flag to note when the frame comes in).  This is still faster than what we had before, because we can move and do other processing after the full frame time passes, but is still slower than doing overlapped triggering.
The next step after this works will be to add overlapped triggering.  That is a bit tricky because we need to be 100% sure we don't drop any frames, or else we can do an entire acquisition with all the remaining frames (after the dropped one(s)) shifted!
Tested by: I ran a local simulation and unit tests pass, but this needs actual testing …
> MultiPointWorker: Use callbacks for image processing so we can trigger faster

- software/control/core/core.py
This improves performance by 12% on my laptop, but with the downside of making the ui less responsive during acquisitions.
Tested by: Running acquisitions on a toupcam system.
> mpw: remove blocking queue on qt signal

- software/control/camera.py
- software/control/camera_hamamatsu.py
- software/control/camera_photometrics.py
- software/control/camera_toupcam.py
- software/control/camera_tucsen.py
- software/control/gui_hcs.py
- software/control/serial_peripherals.py
- software/squid/abc.py
- software/squid/camera/utils.py
The code block in `__del__` in the camera classes can not be reached due to some segmentation fault. For now we will explicitly close cameras on exiting software.
> close cameras explicitly on exit

- software/configurations/configuration_Squid+_H117_ORCA.ini
- software/control/camera.py
- software/squid/config.py
This pull request includes updates to configuration files and camera-related code to enhance functionality and ensure compatibility with additional hardware. The most important changes involve adjustments to homing and position limits in the configuration file, as well as support for a new camera model.
* [`software/configurations/configuration_Squid+_H117_ORCA.ini`](diffhunk://#diff-60d10781037ed93624c6ffe737893efe804d2cc1ed2a50885c749610a4f143e2L113-R113): Changed `homing_enabled_z` from `True` to `False`, and updated software position limits for X, Y, and Z axes to refine movement boundaries. [[1]](diffhunk://#diff-60d10781037ed93624c6ffe737893efe804d2cc1ed2a50885c749610a4f143e2L113-R113) [[2]](diffhunk://#diff-60d10781037ed93624c6ffe737893efe804d2cc1ed2a50885c749610a4f143e2L222-R227) …
> bug fix: Prior stage config update; Daheng camera model support

- software/control/gui_hcs.py
- software/control/widgets.py
Tested in simulation mode
This pull request refactors the handling of microscope mode selection in the `software/control` module, replacing index-based selection with name-based selection for improved clarity and maintainability. The changes primarily affect signal connections and method definitions in the `gui_hcs.py` and `widgets.py` files.
* **Signal connections updated to use name-based selection**:
- In `gui_hcs.py`: Updated signal connections in `makeConnections` and `slot_settings_changed_laser_af` to use `select_new_microscope_mode_by_name` instead of `update_microscope_mode_by_name`. [[1]](diffhunk://#diff-b32c2c591f7e7074dc4393294e5993027fa1de4429b34dbf8e760d697b2c7219L1070-R1075) [[2]](diffhunk://#diff-b32c2c591f7e7074dc4393294e5993027fa1de4429b34dbf8e760d697b2c7219L1134-R1134) …
> bug fix: gui connections for selecting microscope mode

- software/control/_def.py
- software/control/utils.py
This pull request introduces a new focus measure method, `TENENGRAD`, to enhance the calculation of focus measures for images. Additionally, it includes a minor cleanup of a comment in the `FOCUS_MEASURE_OPERATOR` definition.
* [`software/control/utils.py`](diffhunk://#diff-5cc827e63be4a68ecf96663b01f88bca923d92292e6b1c54c6a4174beb53a82eR59-R62): Added support for the `TENENGRAD` method in the `calculate_focus_measure` function, which uses Sobel operators to compute focus measure based on image gradients.
* [`software/control/_def.py`](diffhunk://#diff-def41afca339c9319b94636b379bd2c544c5fb81b6e8a37e4d732bdc05fffb97L551-R551): Removed outdated comment regarding the `FOCUS_MEASURE_OPERATOR` default value while retaining the existing "LAPE" method.
> add Tenengrad focus measure option

- software/control/gui_hcs.py
Tested in simulation mode
This pull request introduces a user-friendly enhancement to the `software/control/gui_hcs.py` file. Specifically, it adds a confirmation dialog to the `closeEvent` method to ensure users confirm their intent to exit the software.
User experience improvement:
* [`software/control/gui_hcs.py`](diffhunk://#diff-b32c2c591f7e7074dc4393294e5993027fa1de4429b34dbf8e760d697b2c7219R1663-R1675): Added a confirmation dialog in the `closeEvent` method to prompt users with a "Confirm Exit" message before closing the software. If the user selects "No," the event is ignored, preventing accidental exits.
> show a dialog for confirmation on close

- software/control/gui_hcs.py
As we removed the moving stage step before shutting down, the current clearing strategy may result a collision of the plate clamp post and transillumination arm. To fix this, home x first before the +20 move, so x will be somewhere in between the loading position and the transillumination arm.
Tested on a Cephla stage.
> home x first to make sure stage is clear for homing

- software/control/camera_tucsen.py
- software/control/widgets.py
This pull request introduces support for the FL26BW camera model in the `camera_tucsen.py` module and updates the widget interface to handle analog gain dynamically based on camera capabilities. The changes primarily focus on adding functionality specific to the FL26BW model, refining analog gain handling, and ensuring compatibility across camera models.
* [`software/control/camera_tucsen.py`](diffhunk://#diff-86d87aef2b0cd7acf6202266f1cd80bd968b14fbc643ebc6c23475ab3d0372f5R153-R157): Added logic to set the camera mode (`STANDARD` or `SENBIN`) based on the binning configuration for the FL26BW model. Default modes for other models remain unchanged. [[1]](diffhunk://#diff-86d87aef2b0cd7acf6202266f1cd80bd968b14fbc643ebc6c23475ab3d0372f5R153-R157) …
> updated Tucsen FL26-BW camera support

- software/control/core/core.py
- software/control/gui_hcs.py
This pull request introduces a new "Well Selector" feature to the application's user interface. The changes include adding a toggle button for the Well Selector, updating its visibility logic based on the active tab and acquisition state, and ensuring its state is preserved across tab switches. The most important changes are grouped into UI enhancements and logic updates.
* Added a new toggle button `btn_well_selector` in `software/control/core/core.py` to allow users to show or hide the Well Selector. The button is integrated into the status layout alongside existing controls. [[1]](diffhunk://#diff-2fc90167f3cd3e8a6b36bdd78086c6ae5811054d9f87239fa2fe2b3a8858d691R2949-R2952) [[2]](diffhunk://#diff-2fc90167f3cd3e8a6b36bdd78086c6ae5811054d9f87239fa2fe2b3a8858d691L2959-R2965)
* Introduced a …
> add a button to show/hide well selector

- software/control/core/multi_point_worker.py
This pull request includes a fix to the `acquire_at_position` method in `multi_point_worker.py`. The change removes the requirement of `self.do_reflection_af` flag so we can save characterization images when laser AF is not enabled.
Tested in simulation mode.
> use characterization mode when laser af is not enabled

- software/control/camera.py
Before, we weren't updating the strobe delay properly and we were setting the camera exposure time incorrectly in the software trigger case.  
This fixes both of those.
We still observed issues with early-row darkness when using hardware triggering, and some potential timing issues related to hardware triggering in live mode.  Although those seem like separate issues (aka: the fixes here are definitely needed!).
Tested by: acquisitions on an octopi with both software and hardware triggering.
> cameras: default: fix strobe and exposure

- software/control/gui_hcs.py
Before, we'd calculate this for the entire display area.  If a user was using a multi screen setup that had monitors that didn't line up perfectly, they could get an unusable window.  This now only calculates the window size based on the primary display size.
Tested by: Running on a system with multiple monitors and making sure the main window is now usable.
> gui: use the primary screen for initial window size

- software/control/core/multi_point_worker.py
See title.  This is maybe not the exact right fix, but it does work.  The issue is that the QTimer might be running its callback when we stop, so one image may sneak through.  This can then get into the callback at acquisition start (and so you get an error about capture info not existing at the start of an acquisition).
Tested by: Running a bunch of acquisitions with live mode enabled to start, and observing the WARNING prints.
> MultiPointWorker: protect against in flight triggering

- software/control/core/channel_configuration_mananger.py
- software/control/core/configuration_mananger.py
- software/control/core/contrast_manager.py
- software/control/core/core.py
- software/control/core/laser_af_settings_manager.py
- software/control/core/live_controller.py
- software/control/core/objective_store.py
- software/control/core/stream_handler.py
- software/control/gui_hcs.py
- software/control/lighting.py
- software/control/microcontroller.py
- software/control/microscope.py
- software/control/serial_peripherals.py
- software/control/widgets.py
- software/main_hcs.py
- software/squid/stage/utils.py
- software/tests/control/gui_test_stubs.py
- software/tests/control/test_HighContentScreeningGui.py
- software/tests/control/test_MultiPointController.py
- software/tests/control/test_MultiPointWorker.py
- software/tests/control/test_microcontroller.py
- software/tests/control/test_microscope.py
- software/tools/microscope_stress_test.py
This is step 1 in creating our fully-headless `Microscope` object.  By this, we mean that Qt is never imported and no ui library is needed.
Tested By:
1. Local sim testing
2. Testing on a toupcam system with no laser AF
3. Testing on a toupcam system with laser AF
4. grepping for `liveController.*` uses, and checking they migrated properly
5. `pytest -m tests`
6. For laser AF: click all laser AF buttons
7. For cameras: Try adjusting camera settings
8. For live + acquisitions: acquisitions with laser af, contrast af, no af, mutli channel.  I verified I can abort aquisitions still, and that all images are saved as expected.
> headless: reverse relationship between gui <-> microscope so we can have a truly headless api

- software/control/core/core.py
This is a temporary solution. We'll use one interface for all filter wheel soon.
This pull request introduces updates to the `update_illumination` method in the `core.py` file to enhance compatibility with the Dragonfly microscope system while maintaining support for existing configurations. The most important changes involve conditional logic adjustments and the addition of new functionality for setting the emission filter position when using Dragonfly.
* Updated the conditional check for spinning disk confocal systems to exclude Dragonfly by adding `and not USE_DRAGONFLY` to the condition. This ensures the correct emission filter logic is applied based on the hardware in use. (`[software/control/core/core.pyL508-R508](diffhunk://#diff-2fc90167f3cd3e8a6b36bdd78086c6ae5811054d9f87239fa2fe2 …
> use emission filter wheel in live controller

- software/control/core/core.py
- software/control/serial_peripherals.py
- software/control/widgets.py
This pull request introduces updates to the microscope control system, focusing on improving the handling of camera ports, dichroic positions, and emission filters. Key changes include enhancing the logic for determining the camera port, updating emission filter handling, and simplifying field aperture selection in the user interface.
* [`software/control/serial_peripherals.py`](diffhunk://#diff-44ed897ed53a1d092c75d43a3ab81a26266124c1d153a2f223dda9552f8347d7L535-R551): Added `get_camera_port` to determine the current camera port based on dichroic position and its associated information. This method raises an error if the port cannot be determined.  
* [`software/control/serial_peripherals.py`](diffhunk://#diff-44ed897ed53a1d092c75d43a3ab81a26266124c1d153a2f223dda9552f8347d7L535-R551): …
> bug fix: select camera port for changing filter wheel position

- software/control/widgets.py
This pull request makes minor adjustments to the initialization of UI layouts in the `widgets.py` file to improve consistency and avoid passing the parent widget unnecessarily. These changes simplify the layout creation process.
* [`software/control/widgets.py`](diffhunk://#diff-26413fa85447f35aa4077535ae2d5f6f1905d5de96d6b303d426f9d039ddde2bL994-R996): Removed the parent widget argument (`self`) when initializing `QVBoxLayout`, `QHBoxLayout`, and `QGridLayout` in the `init_ui` method. This ensures a cleaner and more consistent approach to layout initialization. [[1]](diffhunk://#diff-26413fa85447f35aa4077535ae2d5f6f1905d5de96d6b303d426f9d039ddde2bL994-R996) [[2]](diffhunk://#diff-26413fa85447f35aa4077535ae2d5f6f1905d5de96d6b303d426f9d039ddde2bL1012-R1012)
> bug fix: qt widget layout error

- software/control/camera_tucsen.py
- software/squid/config.py
Tested on Windows. Hardware trigger tested.
This pull request adds support for two new Tucsen camera models to the configuration module. The changes expand the available camera options for the application.
Camera model support:
* Added `ARIES_6506` and `ARIES_6510` to the `TucsenCameraModel` enum in `software/squid/config.py`, allowing these models to be recognized and used in the codebase.
> cameras: Tucsen Aries series support (genicam)

- software/control/gui_hcs.py
- software/control/microcontroller.py
- software/control/microscope.py
This pull request refactors how and where the DAC gain configuration for the objective piezo is handled, moving related logic from the GUI hardware setup to the microscope's preparation phase and ensuring DAC scaling for illumination is always set during microcontroller initialization. This makes hardware initialization more modular and robust.
Hardware initialization refactoring:
* Moved DAC gain configuration for the objective piezo out of `setup_hardware` in `gui_hcs.py` and into the `prepare_for_use` method of `Microscope`, ensuring it only runs when needed and making the code more modular. [[1]](diffhunk://#diff-b32c2c591f7e7074dc4393294e5993027fa1de4429b34dbf8e760d697b2c7219L485-L490) [[2]](diffhunk://#diff-0335b71615d885047310f61f8354ce70de2d0913b37a44489c8867df347677a8L211-R216) …
> move microcontroller initialization code out of gui

- software/control/core/live_controller.py
We were calling `_start_new_timer()` unconditionally in LiveController when we set trigger fps. On start this was called and turned on illumination. Added `if self.is_live:` to start timer only when live is on.
> bug fix: illumination always turns on when software starts

- software/control/core/laser_auto_focus_controller.py
This pull request introduces an important improvement to the laser auto-focus controller's spot detection logic and removes an unused method related to clearing the reference position. The main change adds a check to ensure that detected laser spots are within the allowed range, improving reliability and safety.
Laser spot detection enhancements:
* Added a validation step in `_get_laser_spot_centroid` to skip and warn if the detected spot is outside the allowed range from the reference position, based on `laser_af_range` and pixel-to-micron conversion.
Code cleanup:
* Removed the `clear_reference` method from the controller, which is not being used anywhere.
> bug fix: laser af using other spots in averaging

- software/control/core/laser_auto_focus_controller.py
- software/control/widgets.py
Tested in simulation mode.
This pull request improves the robustness and user feedback of the laser autofocus and Z-range controls in the application. The main changes add checks to ensure the laser autofocus system is initialized before attempting to set a reference, and provide clear error messages to the user if initialization has not occurred. Additionally, the user interface now disables the reflection autofocus checkbox when Z-range controls are visible to prevent conflicting operations.
**Laser Autofocus Initialization Checks and Error Handling:**
* Added a check in `LaserAutoFocusController.set_reference` to ensure the controller is initialized before proceeding. If not initialized, an error is logged and the method returns `False`.
* In multiple places in `widgets.py` (e.g., …
> feat: set laser af reference when setting z min in z range
