Cephla-Lab/Squid

- software/control/microcontroller.py
This is just opportunistic code cleanup while I was in the area.
Tested By: Running in sim mode.
> microcontroller: combine the move commands via a helper

- software/control/gui_hcs.py
Before, our gui wait function without an argument would just hang forever if a command didn't complete.  Now, all waits time out at some point.  And if a wait times out during gui initialization, we reset the micro and re-throw.
We still aren't closing down properly because (I think) the main thread isn't where this throws.  But it is at least really clear in the terminal that initialization timed out.
This also makes it so other actions that use the wait functions in the gui can time out.  For the most part, this means the gui can continued to be used (but in-progress actions will likely continue!).
> gui_hcs: if the microcontroller times out during initialization, reset it before failing

- software/control/core.py
- software/control/gui_hcs.py
adding click to move in the navigation viewer
> click-to-move in navigationViewer

- software/control/core.py
click-to-move navigation viewer bug: offset issue fixed
> click-to-move navigation viewer offset

- software/control/core.py
- software/control/gui_hcs.py
- software/control/widgets.py
- self.region_centers {region_id: [x_mm, y_mm, z_mm]}
- self.region_fov_coordinates {region_id: [(fov_x_mm, fov_y_mm, fov_z_mm)...]}
- add_region(well_id, center_x, center_y, scan_size_mm, overlap_percent, shape)
- remove_region(well_id) → cleans up region data and overlays
- clear_regions() → resets all region data
- update_fov_z_level(region_id, fov_index, new_z_mm)
- validate_coordinates(x_mm, y_mm) → checks SOFTWARE_POS_LIMIT bounds
- validate_region(region_id) → verifies region in both dictionaries
- get_region_bounds(region_id) → returns {min_x, max_x, min_y, max_y}
from flexibleMultiPointWidget:
- add_flexible_region(region_id, x_mm, y_mm, z_mm, Nx, Ny, overlap_percent)
- add_flexible_region_with_step_size(region_id, x_mm, y_mm, z_mm, Nx, Ny, dx_mm, dy_mm)
from …
> pulled out region_coordinates from MultiPointWidgets into ScanCoordinates 

- software/control/filterwheel.py
- software/control/microcontroller.py
- software/squid/config.py
- software/squid/stage/cephla.py
> fix a bug of axis move direct

- software/control/console.py
- software/control/core/core.py
- software/control/gui_hcs.py
- software/control/widgets.py
- software/squid/stage/prior.py
- software/squid/stage/utils.py
See title.
Tested by: If the linting action passes, this is good to go.
> fix(formatting): Run black on whole repo again to get to clean lint state

- software/control/core/core.py
- software/control/widgets.py
Added new scan shape. Width/height ratio for the rectangle is hard-coded in `core.py -> ScanCoordinates -> add_region`. Currently not used in any default sample format yet.
>  New scan shape: Rectangle

- software/control/widgets.py
This is a temporary fix - we shouldn't be hard coding indicies!
Tested by: Manual mode works in sim now.
> manual roi: fix incorrect index

- software/squid/stage/prior.py
The timer setup before was not actually correct - timers are one shot.  This changes to using a thread instead.
> prior: use a thread instead of timers

- software/control/core/core.py
- software/control/widgets.py
- Hide ''generate focus map"
- Show current fov on top of focus points
- Log the option in `acquisition parameters.json`
Only works in WellplateMultipoint right now
> manual focus map improvements

- software/control/microcontroller.py
The reconnect test was failing because the internal state of the simulated micro was not getting updated properly.  This fixes that.
Tested by: Unit tests should pass now.
> simulated micro: fix to be thread safe

- software/control/core/core.py
- software/control/gui_hcs.py
- software/control/widgets.py
bug fixed:
- widget not using piezo class so the piezo object's current displacement can be wrong
- displayed piezo position can be not up to date when piezo is moved by laser autofocus
> new Piezo class related bug fix

- software/control/core/core.py
Before this acquisition is broken for scopes that do not support laser autofocus. Tested in simulation mode
> fix for acquisitions without laser af

- software/control/gui_hcs.py
See comment in code.
Tested by: I ran 3 different test cases:
Drive the stage to the middle of its travel, and start gui. Make sure homing succeeds.
Drive the stage to within 1mm of the x+y maximum positions, then start the gui. Make sure homing succeeds.
Drive the stage to the loading position, then start the gui. Make sure homing succeeds.
Homing succeeds in all 3. Case 3 is a bit odd since we slide off the loading position suddenly, but it does not appear to cause problems.
> gui: drive y+20, x+20 before homing x+y to make sure we are clear

- software/control/core/core.py
This was missed in the stage refactor, and reported by @hongquanli .
Tested by: The unit tests still pass (not a great signal in this case), and Hongquan is testing it on hardware right now.
> core: SlidePositionControlWorker: fix homing

- software/control/core/core.py
> move back to region center after acquisition (for "glass slide" format)

- software/README.md
- software/control/_def.py
- software/control/camera_hamamatsu.py
- software/control/camera_kinetix.py
- software/control/gui_hcs.py
- software/control/microcontroller.py
- software/drivers and libraries/photometrics/install_photometrics.sh
https://github.com/Photometrics/PyVCAM
Using live mode right now. To set exposure time we need to end live mode and start it again, so there is a significant overhead. Polling temperature causes error in live mode. Live mode seems to consume a lot of resources and it's causing serial buffer max out, so I try to reset the buffer when it's full to get out of the loop. 
This implementation works, but we are also contacting Photometrics tech support to see if it can be improved.
> Kinetix camera support

- software/control/camera_kinetix.py
- software/pyproject.toml
Tested with real camera in simulation mode.
> Kinetix camera: implement gain mode 

- software/control/_def.py
- software/control/camera_toupcam.py
- software/control/core/core.py
- software/control/gui_hcs.py
- software/control/widgets.py
> add configuration variables requested by Arc Institute

- software/control/camera.py
This adds the camera implementation we fall back to when no special camera driver is specified.  As part of adding this, a few camera configs needed to be added (eg: default white balance).
Also, some of the functionality,  like camera temperature, is not supported via this interface.  Right now, these raise `NotImplementedError`.
Tested by: This needs testing on actual hardware.  I don't have a camera I can use it with right now.  The gui does start and run on HW using other cameras, but we need to test with one of these cameras.
> cameras: add the default gxipy camera implementation

- software/control/camera_hamamatsu.py
- software/control/core/core.py
- software/control/gui_hcs.py
- software/control/hama_one_thread.py
- software/control/hama_repro.py
- software/control/microscope.py
- software/control/utils.py
- software/control/widgets.py
- software/squid/camera/utils.py
- software/tools/hamamatsu_test.py
This adds a Hamamatsu driver implementation that matches or exceeds the existing implementation, although this still leaves a bunch of functionality as `NotImplementedError`.
This is untested and 100% has issues - we need to test and debug those issues with Hamamatsu hardware.
Tested By: Untested!
> cameras: Add the Hamamatsu camera implementation

- software/control/core/core.py
- software/control/gui_hcs.py
- software/control/hama_one_thread.py
- software/control/microscope.py
- software/control/widgets.py
- software/squid/config.py
This is just running `black --config pyproject.toml .`
Tested by: linting passes now.
> formatting: fix formatting after merging all the camera prs

- software/control/core/core.py
- software/control/gui_hcs.py
- software/control/widgets.py
Fix errors for the 1536 wellplate widget: 1) starting program with 1536 wellplate as default sample format 2) signal connection for movements/selection 3) well id sorting error
Tested
> fix 1536 well plate error

- software/control/core/core.py
- software/control/gui_hcs.py
- software/control/microscope.py
This removes a bunch of unused code, converts a bunch of prints to logging, and does general cleanup.
Tested by: Tested on hardware and unit tests.
> core&gui: cleanup, delete unused, and fix prints

- software/control/_def.py
- software/control/core/core.py
- software/control/custom_multipoint_widget.py
- software/control/gui_hcs.py
- software/control/widgets.py
This pull request introduces a new feature for handling template-based multipoint scanning in the software control system. It includes the addition of a `TemplateMultiPointWidget` class, updates to the GUI to integrate this widget, and several refactorings to improve layout management and modularity.
* **`TemplateMultiPointWidget` Class**: A new widget extends `FlexibleMultiPointWidget` to support loading and applying templates for predefined scanning positions. It includes UI components for loading templates, selecting templates, and adding positions based on templates.
* **Integration into GUI**: The `TemplateMultiPointWidget` is conditionally loaded and added to the record tab in the GUI if `USE_TEMPLATE_MULTIPOINT` is enabled. …
> feat: add template multipoint

- software/control/core/core.py
- software/control/microscope.py
1) added more hardware support 2) removed redundant code in setting channel mode 3) fixed camera errors
Tested in simulation mode.
> Headless mode improvement

- software/control/gui_hcs.py
- software/squid/abc.py
Restore previous commit overwritten by merge conflicts. Fix inconsistent text.
Tested in simulation mode
> restore DEFAULT_TRIGGER_MODE

- software/control/core/core.py
- software/control/widgets.py
add get_channel_configuration_by_name() in ChannelConfigurationManager to simplify usages
> use get_channel_configuration_by_name

- software/control/microcontroller.py
This is technically "better" because it doesn't busy wait, and should finish waiting faster, and is thread safe.
Empirically in testing it didn't change anything, though.  So it's just a draft for comment for now.
Tested by: Running the following:
```
$ python tools/stage_timing.py --start 1.005 --step 0.030 --axis=z --count 100
$ python tools/microcontroller_stress_test.py --laser_af --stage --runtime 20
```
> microcontroller: use a cv for wait instead of sleep and poll

- software/control/microscope.py
> microscope: fix incorrect _log attribute use and init order

- software/control/core/core.py
- software/control/gui_hcs.py
- software/control/lighting.py
- software/control/widgets.py
- software/setup_22.04.sh
- software/tools/evaluate_intensity_calibration.py
- software/tools/generate_intensity_calibrations.py
- software/tools/test_intensity_calibration.py
This pull request includes several updates to improve code maintainability, simplify function calls, and enhance functionality in the illumination control and surface fitting workflows. Key changes include renaming methods for better clarity, removing redundant code, adding new functionality for illumination control, and refactoring imports in calibration tools.
* Renamed `_set_illumination` to `set_illumination` and updated all references to the renamed method for better clarity and consistency. (`software/control/core/core.py`, [[1]](diffhunk://#diff-2fc90167f3cd3e8a6b36bdd78086c6ae5811054d9f87239fa2fe2b3a8858d691L466-R466) [[2]](diffhunk://#diff-2fc90167f3cd3e8a6b36bdd78086c6ae5811054d9f87239fa2fe2b3a8858d691L700-R700)
* Enhanced `set_intensity` to handle `ShutterControlMode.TTL` by …
> bug fix for PR #175, #214 and a few other improvements

- software/control/core/core.py
Tested by simulations
1. add `self.update_line_profile()` to `display_image` for live line profile update
2. add code to enable line profiler button after the first image is displayed
3. identify angle from `self.line_roi.getState()` is in degrees where `np.cos()` expects radian and fix the issue
4. use `LineROI` instead of `LineSegmentROI`
5. instructions on providing visual feedback for drawing the line
This pull request introduces a new "Line Profiler" feature to the `software/control/core/core.py` file, allowing users to draw a line on an image and analyze the intensity profile along that line. The changes include UI updates, new methods for line drawing and profiling, and integration with existing image display functionality.
* **UI Enhancements**:
- Added a toggle button …
> add line profiler

- software/control/utils.py
- software/tests/control/test_utils.py
This is a debugging tool for capturing timing information.  We'll likely evolve it over time, but for now it helps us capture reliable timing information.
Tested by: unit tests.
> utils: TimingManager and Timer helper

- software/control/core/multi_point_worker.py
This is important for the ui since we can now be moving significantly at some points when we used to not be.  In general, we don't want to use `get_pos()` on the stage outside of the real moments when we care about the current position.
Tested by: Running acquisition on a squid.
> MultiPointWorker: Use trigger-time and move-time positions throughout.  Do not recapture.

- software/control/core/multi_point_worker.py
This is just from running black on the repo.  A few slipped through in the rebase madness.
Tested by: Black passes cleanly.
> formatting: fix after merge train

- software/control/camera.py
- software/control/gui_hcs.py
This pull request introduces enhancements to camera control and GUI behavior, focusing on improving white balance handling and refining navigation viewer logic for specific conditions.
* [`software/control/camera.py`](diffhunk://#diff-1f0ea86f2716d10c7fac39432a662c1ba9cb884c850a7f46602fbbc8805473f4R117-R118): Added a call to `set_auto_white_balance_gains(False)` in the `__init__` method to ensure auto white balance gains are disabled by default, aligning with manual white balance configuration.
* [`software/control/gui_hcs.py`](diffhunk://#diff-b32c2c591f7e7074dc4393294e5993027fa1de4429b34dbf8e760d697b2c7219L269-R269): Updated the condition for initializing `NavigationViewer` to include `IS_HCS` alongside `WELLPLATE_FORMAT == "glass slide"`, ensuring the viewer is only created when …
> Octopi bug fix

- software/control/core/multi_point_worker.py
After discussion with @hongquanli , we decided that for all but HARDWARE trigger acquisitions, we'll go back to waiting for frames to come in before turning off illumination.  This deals with the non-determinism we are seeing in the SW triggering across cameras.
Tested by: Running a small 2 channel acqusition with 3 z and 2 timepoints.  Mosaic views appear correct.  Acquisition image folders appear correct as well.
> acquisitions: wait for frames when using non-hw triggering

- software/control/Xeryon_settings.txt
- software/control/objective_changer_2_pos_controller.py
These changes could possibly fix some issues for the Xeryon stage. We don't know the reason yet, but it works for some cases.
> update Xeryon stage settings

- software/control/core/scan_coordinates.py
- software/control/gui_hcs.py
- software/control/widgets.py
A quick fix for making flexible multipoint work. Tested in simulation mode.
This pull request introduces improvements to how Z-coordinates are handled in the scan coordinate and location list management features. The main changes include adding a new "Update Z" button for updating Z values, standardizing Z units to millimeters throughout the import/export process, and ensuring Z-coordinates are included in relevant data structures.
**UI and Functionality Improvements:**
* Added a new `Update Z` button to the location list interface, replacing the previous "Edit" button, and connected it to a new `update_z` method for updating Z values of selected locations. [[1]](diffhunk://#diff-26413fa85447f35aa4077535ae2d5f6f1905d5de96d6b303d426f9d039ddde2bL2783-R2784) …
> bug fix: Flexible Multipoint Widget
